mongo:
  uri: "mongodb://tianjun:1qaz2WSX@120.25.170.193:27017/"
dangdang:
  username: "13883884201"
  password: "tianjun223."
baidu:
  username: "13883884201"
  password: "tianjun223."
crawler:
  thread: 5
  remote: "http://selenium:4444"