version: "3.3"  # optional since v1.27.0
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:4.1.1-20211217
#    image: selenium/standalone-firefox:4.1.1-20211217
    restart: always
    shm_size: 2gb
    ports:
      - "4444:4444"

  crawler:
    build: .
    container_name: crawler
    restart: always
    working_dir: /code
    volumes:
      - .:/code
